### ISSUE TITLE
[2주차] 과제

### ISSUE THREAD

**Issue by HEHEEUN** [AND-SOPT-iOS/KimHeeEun#3]
## Description

2주차 과제 구현하기 : 앱스토어 TOSS 화면 구현하기

## TODO

- [ ] 좌우 여백 20으로 통일 !!
- [ ] 스크롤로 리뷰 작성 버튼까지 진행
- [ ] 컴포넌트 배치 위주로 구현
- [ ] 버전 기록을 누를 경우 버전 기록 페이지로 이동
- [ ] 미리보기에는 이미지가 하나 나오도록 구현
- [ ] 평가 및 리뷰 모두 보기 클릭 시 모두 보기 페이지로 이동
