### ISSUE TITLE
[3주차] 과제

### ISSUE THREAD

**Issue by HEHEEUN** [AND-SOPT-iOS/KimHeeEun#5]
## Description

2주차 과제 구현하기 : 앱스토어 TOSS 화면 구현하기

## TODO

1. 금융페이지
- [ ] 1번 섹션 : 
- [ ] 2번 섹션
- [ ] 3번 섹션
- [ ] 4번 섹션

2. 인기 차트

- [ ] 랭킹 20위까지 구현
- [ ] 토스 셀 선택 시 2주차 뷰컨으로 이동

3. 상세페이지

- [ ] 이미지 미리보기 5개 구현
- [ ] 평가 슬라이드 구현 : 데이터 3개

## Issue 

1. 금융페이지
- [ ] 1번 섹션 : 페이지 개수 4개 : 좌우 스크롤 가능
- [ ] 2번 섹션 : 페이지 개수 4개 : 좌우 스크롤 가능
- [ ] 4번 섹션 : 토스 셀 선택 시 이동
- [ ] 4번 섹션 : 모두보기 클릭 시 이동

2. 인기 차트
- [ ] 랭킹 20위까지 구현
- [ ] 토스 셀 선택 시 이동

3. 상세페이지
- [ ] 이미지 미리보기 5개 삽입
- [ ] 평가 슬라이드 구현 : 데이터 3개
